name: Контроль качества

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sonar:
    if: github.repository_owner == 'stivo182'
    uses: autumn-library/workflows/.github/workflows/sonar.yml@v1
    with:
      github_repository: Stivo182/depos
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}